services:
  backend:
    build:
      context: ./server/Backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./server/Backend:/app
    restart: always

  frontend:
    build:
      context: ./server/UI
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./server/UI:/app
    restart: always
