versionversion: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - frontend

  frontend:
    build:
      context: ./UI
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./UI:/app
